# Copyright 2021 Roxy Light
# SPDX-License-Identifier: ISC

name: Publish
on:
  release:
    types: [published]
permissions: {}
jobs:
  go-get:
    name: go get
    runs-on: ubuntu-latest
    steps:
    - name: Fetch release from proxy
      run: |
        curl -fsSL "https://proxy.golang.org/zombiezen.com/go/sqlite/@v/$(echo "$GITHUB_REF" | sed -e 's:^refs/tags/::').info"
